name: Android Release

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Change this line to use 'temurin'
          java-package: jdk
          architecture: x64
          check-latest: false


      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Build release APK/AAB
        run: ./gradlew assembleRelease

      - name: Upload Release APK/AAB to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/outputs/bundle/release/app-release.aab  # Path to your AAB file
            # Uncomment and modify the following line if you want to upload APK as well
            app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
